-- Seed catalogue: 24 books. The first eight carry an ISBN and a description.
INSERT INTO book (id, title, author, category, price_inr, isbn, published_at, description, cover_url,
                  rating, rating_count, popularity, created_at, updated_at)
VALUES
    ('clean-code-in-java', 'Clean Code in Java', 'Ananya Rao', 'JAVA', 999.00, '9789350000014', DATE '2025-11-04',
     'Write Java that your teammates can read on the first pass: naming, small methods, honest tests and refactoring without fear, with examples drawn from real Spring services.',
     '/assets/images/book-cover-clean-code-in-java.jpg', 4.8, 1284, 100, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('mastering-react-19', 'Mastering React 19', 'Kabir Mehta', 'JAVASCRIPT', 1299.00, '9789350000021', DATE '2026-02-18',
     'A hands-on tour of React 19 covering actions, the new hooks, Suspense-driven data loading and the patterns that keep large component trees fast.',
     '/assets/images/book-cover-mastering-react-19.jpg', 4.7, 986, 99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('system-design-interview-handbook', 'System Design Interview Handbook', 'Maya Srinivasan', 'SYSTEM_DESIGN', 1499.00, '9789350000038', DATE '2025-06-30',
     'A structured approach to system design interviews, from clarifying requirements to sketching scalable architectures. Includes 20 worked problems with trade-off discussions.',
     '/assets/images/book-cover-system-design-interview-handbook.jpg', 4.9, 2418, 98, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('docker-kubernetes-in-practice', 'Docker & Kubernetes in Practice', 'Rohan Iyer', 'DEVOPS', 1299.00, '9789350000045', DATE '2025-09-12',
     'Package, ship and run services with Docker and Kubernetes. Covers images, deployments, networking and the operational habits that keep clusters healthy.',
     '/assets/images/book-cover-docker-kubernetes-in-practice.jpg', 4.6, 742, 97, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('python-for-data-engineers', 'Python for Data Engineers', 'Neha Kulkarni', 'PYTHON', 999.00, '9789350000052', DATE '2026-01-22',
     'Build dependable batch and streaming pipelines in Python. Covers data modelling, testing pipelines and orchestrating jobs in production.',
     '/assets/images/book-cover-python-for-data-engineers.jpg', 4.8, 1106, 96, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('typescript-patterns-at-scale', 'TypeScript Patterns at Scale', 'Arjun Desai', 'JAVASCRIPT', 799.00, '9789350000069', DATE '2025-04-08',
     'Type-level patterns for large TypeScript codebases: discriminated unions, generics that stay readable, and module boundaries that scale with the team.',
     '/assets/images/book-cover-typescript-patterns-at-scale.jpg', 4.5, 628, 95, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('building-reliable-llm-applications', 'Building Reliable LLM Applications', 'Ishita Banerjee', 'AI_ML', 1499.00, '9789350000076', DATE '2026-03-10',
     'Design, evaluate and operate applications built on large language models, with practical guidance on prompting, retrieval, guardrails and monitoring.',
     '/assets/images/book-cover-building-reliable-llm-applications.jpg', 4.7, 834, 94, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('postgresql-performance-field-guide', 'PostgreSQL Performance Field Guide', 'Vikram Shah', 'DATABASES', 799.00, '9789350000083', DATE '2025-08-01',
     'Find and fix slow PostgreSQL queries: reading EXPLAIN plans, choosing indexes, tuning configuration and keeping vacuum under control.',
     '/assets/images/book-cover-postgresql-performance-field-guide.jpg', 4.6, 519, 93, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('clean-code-in-java-workbook', 'Clean Code in Java: Workbook', 'Ananya Rao', 'JAVA', 599.00, NULL, DATE '2026-04-02',
     NULL,
     '/assets/images/book-cover-clean-code-in-java.jpg', 4.6, 312, 80, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('mastering-react-19-server-components', 'Mastering React 19: Server Components', 'Kabir Mehta', 'JAVASCRIPT', 1099.00, NULL, DATE '2026-05-14',
     NULL,
     '/assets/images/book-cover-mastering-react-19.jpg', 4.6, 401, 79, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('system-design-interview-handbook-vol-2', 'System Design Interview Handbook, Vol. 2', 'Maya Srinivasan', 'SYSTEM_DESIGN', 1499.00, NULL, DATE '2026-01-09',
     NULL,
     '/assets/images/book-cover-system-design-interview-handbook.jpg', 4.8, 1037, 78, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('docker-kubernetes-in-practice-labs', 'Docker & Kubernetes in Practice: Labs', 'Rohan Iyer', 'DEVOPS', 899.00, NULL, DATE '2025-12-03',
     NULL,
     '/assets/images/book-cover-docker-kubernetes-in-practice.jpg', 4.4, 288, 77, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('python-for-data-engineers-exercises', 'Python for Data Engineers: Exercises', 'Neha Kulkarni', 'PYTHON', 699.00, NULL, DATE '2026-02-27',
     NULL,
     '/assets/images/book-cover-python-for-data-engineers.jpg', 4.5, 254, 76, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('typescript-patterns-at-scale-case-studies', 'TypeScript Patterns at Scale: Case Studies', 'Arjun Desai', 'JAVASCRIPT', 899.00, NULL, DATE '2025-10-19',
     NULL,
     '/assets/images/book-cover-typescript-patterns-at-scale.jpg', 4.4, 197, 75, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('building-reliable-llm-applications-evaluation', 'Building Reliable LLM Applications: Evaluation', 'Ishita Banerjee', 'AI_ML', 1199.00, NULL, DATE '2026-05-28',
     NULL,
     '/assets/images/book-cover-building-reliable-llm-applications.jpg', 4.6, 366, 74, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('postgresql-performance-field-guide-indexing', 'PostgreSQL Performance Field Guide: Indexing', 'Vikram Shah', 'DATABASES', 699.00, NULL, DATE '2026-03-21',
     NULL,
     '/assets/images/book-cover-postgresql-performance-field-guide.jpg', 4.7, 241, 73, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('clean-code-in-java-refactoring-katas', 'Clean Code in Java: Refactoring Katas', 'Devika Nair', 'JAVA', 1199.00, NULL, DATE '2026-06-05',
     NULL,
     '/assets/images/book-cover-clean-code-in-java.jpg', 4.5, 173, 60, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('mastering-react-19-testing-playbook', 'Mastering React 19: Testing Playbook', 'Farhan Qureshi', 'JAVASCRIPT', 999.00, NULL, DATE '2026-04-19',
     NULL,
     '/assets/images/book-cover-mastering-react-19.jpg', 4.3, 142, 59, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('python-for-data-engineers-pipelines-cookbook', 'Python for Data Engineers: Pipelines Cookbook', 'Pooja Menon', 'PYTHON', 899.00, NULL, DATE '2026-05-02',
     NULL,
     '/assets/images/book-cover-python-for-data-engineers.jpg', 4.4, 119, 58, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('docker-kubernetes-in-practice-security', 'Docker & Kubernetes in Practice: Security', 'Siddharth Rao', 'DEVOPS', 1099.00, NULL, DATE '2026-06-21',
     NULL,
     '/assets/images/book-cover-docker-kubernetes-in-practice.jpg', 4.2, 97, 57, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('designing-event-driven-systems', 'Designing Event-Driven Systems', 'Maya Srinivasan', 'SYSTEM_DESIGN', 1299.00, NULL, DATE '2025-05-17',
     NULL,
     '/assets/images/book-cover-system-design-interview-handbook.jpg', 4.7, 388, 56, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('kubernetes-operators-explained', 'Kubernetes Operators Explained', 'Rohan Iyer', 'DEVOPS', 1199.00, NULL, DATE '2025-07-23',
     NULL,
     '/assets/images/book-cover-docker-kubernetes-in-practice.jpg', 4.5, 156, 55, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('practical-retrieval-augmented-generation', 'Practical Retrieval-Augmented Generation', 'Ishita Banerjee', 'AI_ML', 1299.00, NULL, DATE '2026-06-30',
     NULL,
     '/assets/images/book-cover-building-reliable-llm-applications.jpg', 4.5, 203, 54, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('sql-tuning-patterns', 'SQL Tuning Patterns', 'Vikram Shah', 'DATABASES', 699.00, NULL, DATE '2025-03-14',
     NULL,
     '/assets/images/book-cover-postgresql-performance-field-guide.jpg', 4.4, 131, 53, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
